apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 5007  # Port exposed within the cluster
      targetPort: 5007  # Port the service forwards traffic to on pods
      nodePort: 31507  # External port exposed on all nodes
  type: NodePort
