apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
      nodePort: 30846
  type: NodePort
