apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
      nodePort: 31482
  type: NodePort
