apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 32742
  type: NodePort
